// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgflencddfhsukwptcjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZmxlbmNkZGZoc3Vrd3B0Y2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NDA4MzMsImV4cCI6MjA1MDQxNjgzM30.kOYy-dwGD0hGhFVclWB7R4R5dZKXxr5BxsAsEzU1R90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);