// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txxfaccdpvoacifuumya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4eGZhY2NkcHZvYWNpZnV1bXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyMDEzNDUsImV4cCI6MjA1MDc3NzM0NX0.92p2KzkVRIVdaQyX3rVVzvqEER7aj5U2LWsLn8xyrjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);